services:
  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    ports:
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/key.pem:/root/ssl/key.pem
      - ./nginx/cert.pem:/root/ssl/cert.pem
    depends_on:
      - frontend-for-test-app
    networks:
      - nc-one-network
  
  frontend-for-test-app:
    build: ./frontend
    container_name: frontend-for-test-app
    ports:
      - 3000:3000
    depends_on:
      - nc-one-back
    networks:
      - nc-one-network

  nc-one-back:
    build: ./backend
    container_name: nc-one-back
    ports:
      - 3001:3000
    volumes:
      - ./static:/usr/src/app/static
    depends_on:
      - mysql
    networks:
      - nc-one-network

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./backend/src/database:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - nc-one-network

networks:
  nc-one-network:
    driver: bridge
